default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:postgres_username) %>
  password: <%= Rails.application.credentials.dig(:postgres_password) %>
  url: <%= Rails.application.credentials.dig(:postgres_url) %>

development:
  <<: *default
  database: dev-bd

test:
  <<: *default
  database: dev-test

production:
  <<: *default
  database: dev-prod
  username: ""
  password: ""